### ISSUE TITLE
Unable to get to work

### ISSUE THREAD

**Issue by marcocarnut** [bpanel-org/bpanel#192]
After installation, the page stops loading with the following  in the browser's console:

 ```
TypeError: bcoin.define is not a function
```

Am I missing something?

**Comment by bucko13** [comment]
Hey Marco,

Sorry to hear you're having trouble and sorry for the delay in getting back to you! I haven't installed bpanel fresh in a while but bcoin has historically been tricky to use with webpack (which is what is running the builds in the background) and has probably become more so since recent updates to the main library have phased webpack support out. I had added some workarounds previously but it's possible these don't work after more recent changes. I'm going to try from scratch myself once more to see what I get and get back to you. It might be the case that the package dependency will need to peg to an earlier version of bcoin instead until perhaps a full refactor can be managed. 

Question: did you install and build using `npm start` or did you try with docker at all instead?

**Comment by bucko13** [comment]
So I was also having some trouble running without docker, but actually it was related to other bcoin related dependencies not building properly (specifically bdb). Docker, on the other hand, did work, probably because the images lock in the builds. Running with docker (instructions in the Readme) I could get an instance of bpanel running from a completely fresh install, so might be worth trying that out first! 

I'll still have to play around with getting npm install and start to work, especially with all of the bcoin changes recently, but in the meantime, at least you should be able to get a dashboard up and running (make sure to give it enough time for the initial build).

**Comment by marcocarnut** [comment]
Yes, I used `npm start` because I had my own container setup.

I managed to get it to work by manually copying this stretch of code in `bpanel-master/node_modules/bcoin/lib/bcoin.js` to `bpanel-master/node_modules/bcoin/lib/bcoin-browser.js`:

```
bcoin.define = function define(name, path) {
  let cache = null;
  Object.defineProperty(bcoin, name, {
    enumerable: true,
    get() {
      if (!cache)
        cache = require(path);
      return cache;
    }
  });                 
};
```

Which I believe shouldn't be necessary.

I ran into other minor snags. I'll retrace my exact steps, restarting from scratch, and will document what I had to do to get it it to work.

**Comment by bucko13** [comment]
Nice. Good find. Yeah this is almost certainly because of changes in bcoin that broke the webpack build. Basically bcoin does its own detection for if it’s being used in a browser or not. This is a problem for webpack though since that isn’t available at build time. There were some custom entrypoints set in the webpack config to get around this, but recent changes may have broken this. Agree that this should not be necessary. The most obvious fix to me would be to harden on a specific commit of bcoin to avoid running into incompatibilities like this, which also shouldn’t be a big deal for the bpanel since many of the changes recently are for IBD improvements on the backend.

**Comment by bucko13** [comment]
Good news! Found the bug and submitted a PR to bcoin to get it fixed. It's minor fix so hopefully should get in quick. https://github.com/bcoin-org/bcoin/pull/926

**Comment by bucko13** [comment]
The PR mentioned above has been merged in and I've updated the package-lock as well. Hopefully it all works now. This also gave me the chance to update some other dependencies that couldn't build in newer versions of node, so thanks for that!

If it's still not working, feel free to re-open and let me know.
