### ISSUE TITLE
Webpack Not Resolving Symlinks

### ISSUE THREAD

**Issue by tynes** [bpanel-org/bpanel#31]
What was the design decision behind this line?

https://github.com/bpanel-org/bpanel/blob/master/webpack.config.js#L61

Seems like it could be the reason why a dev flow around `npm link` doesn't work

**Comment by bucko13** [comment]
Here's one of the threads that reflected a similar problem I was having that was solved when adding this in: https://stackoverflow.com/questions/37769228/npm-link-with-webpack-cannot-find-module (links to the GitHub issues for webpack too). 

Interestingly with `symlink: true` it may solve this problem with local development since it resolves to the real path, but could bring back the other problems with developing with linked modules. npm modules are tricky and webpack can make it trickier. The clearest/easiest solution would be a script to bundle everything. Not ideal though since that's really only necessary for the specific local dev/plugin dependency situation and would require a new dependency for plugin development since we only have babel now. Not a huge deal though and would definitely solve the issue!

Going to close unless you think this might be causing some other problems?
