### ISSUE TITLE
bpanel has a blank screen when opening

### ISSUE THREAD

**Issue by robertclarkson** [bpanel-org/bpanel#66]
![selection_958](https://user-images.githubusercontent.com/3826238/43815334-56ce76e8-9b23-11e8-9c4b-a829baa01958.jpg)

Despite seeing this source code in the code view, the window is just blank

I've got nvm installed and have tried versions 8, 9 and 10 same thing on all versions. I have also downloaded your RC1 and tried that as well with the same problem.

npm --version
6.1.0
node -v
v10.5.0

**Comment by bucko13** [comment]
Since bPanel is essentially a SPA (Single Page App), that's what you'd expect to see for the index.html as all the content is loaded from the main.bundle.js. The first build can take a little while, 30s+, since it has to download the different plugins based on your config file. If you gave it enough time and are still not seeing anything, can you let me know what you're seeing in your JavaScript console? If there were any errors during the build in your console, that would be good too :).

**Comment by robertclarkson** [comment]
![selection_960](https://user-images.githubusercontent.com/3826238/43817652-ac30777a-9b2e-11e8-9000-e57138327231.jpg)

**Comment by robertclarkson** [comment]
husky > failed to install
Command failed: git rev-parse --git-dir
fatal: Not a git repository (or any parent up to mount point /home/rob)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

**Comment by bucko13** [comment]
I just noticed that there has been a problem with our docker hub automated build for the past 5 days. I tried running the default `docker-compose up` and got the same error, presumably because the docker image has an older version of the repo. 

If that is the case, then try the [running without docker](https://bpanel.org/docs/quick-start.html#running-without-docker) setup. You can still use the bcoin docker container though and have bPanel connect to that with `docker-compose up bcoin`. 

If that isn't the case, could you let me know what OS you're using? We've tested with Mac and Linux but not Windows. Also the steps you followed to install and build. 

Sorry for the troubles! Hopefully we'll get you up and running quickly!

**Comment by robertclarkson** [comment]
No worries! Interested to give it a go. Will do your suggestion. I'm on Ubuntu 16.04

**Comment by robertclarkson** [comment]
I was running ```docker-compose up -d bcoin``` and not getting anywhere, then when i used ```docker-compose up bcoin``` The console is now lit up with output, but nothing in the browser on port 80 or port 5000

Also getting console errors:
```bcoin_1      | [debug] (net) Refilling peers (1/8).
bcoin_1      | [debug] (net) Connecting to 122.152.82.91:48444.
bcoin_1      | [debug] (net) Error: Socket Error: ECONNREFUSED (122.152.82.91:48444)```

Do i need to forward this port on my router?

After reading this
```bcoin_1      | [info] (http) Wallet HTTP server listening on 0.0.0.0 (port=48334).```

I tried connecting on 48334 in my browser and I get a HTPASSWD prompt

**Comment by bucko13** [comment]
Hi Robert, I'm sorry to hear you're still having problems. It seems there are a few things that need to be clarified. Hopefully we can clear them up for you!

First, the `-d` option for docker-compose has the container run in [detached mode](https://docs.docker.com/compose/reference/up/) which means it's running but you just won't see anything in your terminal. You would have to check your logs or exec into the docker container to see what's happening. You can confirm it's running however by typing `docker container list` in your terminal.

Second, running `docker-compose up bcoin` _only_ spins up a docker container running a bcoin node. From the [ReadMe](https://github.com/bpanel-org/bpanel#about-the-docker-environment):
> There are three docker services in the compose file: bpanel, bcoin and securityc. The bpanel service is an http server that acts as a static file server and as a request router to backend services as well as a webpack process for building your js files. The bcoin service is an instance of bcoin that supports an http server, a wallet server and a bitcoin p2p server.

The bcoin docker container maps the container's ports to the corresponding ports on your host machine. In the case of a regtest node, that would be `48334`. The node starts with auth on so you need the API key to access, something that bPanel handles for you under the hood if your configs are mapped properly. 

That `ECONNREFUSED` error you are seeing is pretty standard on Regtest since you're not connecting to any real network so they can be ignored.

To get bPanel running locally and connect to your docker container running bcoin, just follow these steps:

1. Run `npm install` in your bpanel project directory
2. Run `docker-compose up -d bcoin` or `docker-compose up bcoin` if you don't want to run in detached mode.* 
3. next run `npm run start:poll -- --client-id=_docker`. 

This last step will start the bPanel server using the `_docker` client configs which should map to docker container's node, and build the app to serve to your browser. Once you see the webpack output confirming the js has been built (could take ~30s for the first build) you should be good to access the app from `localhost:5000`.

You can learn more about these steps as well as the architecture in the docs [here](https://bpanel.org/docs/configuration.html).

Hope this helps! I've also got a PR open (#68) that should fix the problems you were having with the docker image before which would let bpanel work out of the box with `docker-compose up`.

*Alternatively, you can see the logs without attaching the container by running ` docker logs bpanel_app_1 -f --since 1s` after starting the container. To later stop the detached container, run `docker-compose down` from inside the bpanel directory.

**Comment by robertclarkson** [comment]
Thanks for the great response! I'll have another go later.
