### ISSUE TITLE
bcash support

### ISSUE THREAD

**Issue by ap050492** [bpanel-org/bpanel#96]
Does bpanel also support bcash nodes?

**Comment by tynes** [comment]
Yes it does. The latest release supports both bitcoin and bcash

**Comment by bucko13** [comment]
[hsd](https://handshake.org) too if you're interested :). Since bclient can be used to talk both with bcoin and bcash nodes even switching between both btc and bch networks using the same bPanel setup is relatively trivial. There could be a fork of bclient support as the two chains continue to diverge, but we should be able to handle that relatively easily now with the latest release.
